<%@ Page Title="Edit - Delete" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EditPerson.aspx.cs" Inherits="Roladex._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

  

    <div class="row">
         <asp:GridView ID="GridView1" CssClass="Grid" runat="server" AutoGenerateColumns="False" DataSourceID="PersonSQL" AllowPaging="True" AllowSorting="True" 
             BackColor="White" BorderColor="#337AB7" BorderStyle="Solid" BorderWidth="2px" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" 
             AutoGenerateEditButton="True" DataKeyNames="PersonID" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" CellPadding="10">
             <AlternatingRowStyle BackColor="#ededed" />
            <Columns>
                <asp:BoundField DataField="PersonID" HeaderText="PersonID" SortExpression="PersonID" InsertVisible="False" ReadOnly="True" >
                </asp:BoundField>
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" >
                </asp:BoundField>
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" >
                </asp:BoundField>
                <asp:BoundField DataField="CompanyName" HeaderText="CompanyName" SortExpression="CompanyName" >
                </asp:BoundField>
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" >
                </asp:BoundField>
                <asp:BoundField DataField="Phone" HeaderText="Phone" SortExpression="Phone" >
                </asp:BoundField>
                <asp:BoundField DataField="AltPhone" HeaderText="AltPhone" SortExpression="AltPhone" >
                </asp:BoundField>
                <asp:BoundField DataField="Address1" HeaderText="Address1" SortExpression="Address1" >
                </asp:BoundField>
                <asp:BoundField DataField="Address2" HeaderText="Address2" SortExpression="Address2" >
                </asp:BoundField>
                <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" >
                </asp:BoundField>
                <asp:BoundField DataField="State" HeaderText="State" SortExpression="State" >
                </asp:BoundField>
                <asp:BoundField DataField="Zipcode" HeaderText="Zipcode" SortExpression="Zipcode" >
                </asp:BoundField>
            </Columns>
             <FooterStyle BackColor="#337ab7" />
             <HeaderStyle BackColor="#337ab7" Font-Bold="True" ForeColor="White" />
             <PagerStyle BackColor="#337ab7" ForeColor="White" HorizontalAlign="Center" />
             <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
             <SortedAscendingCellStyle BackColor="#dae0ea" />
             <SortedAscendingHeaderStyle BackColor="#012051" />
             <SortedDescendingCellStyle BackColor="#dae0ea" />
             <SortedDescendingHeaderStyle BackColor="#012051" />

        </asp:GridView>
        <asp:SqlDataSource ID="PersonSQL" runat="server" ConnectionString="<%$ ConnectionStrings:RoladexContext %>" 
            SelectCommand="SELECT * FROM [People] ORDER BY [LastName], [FirstName], [CompanyName]"
            UpdateCommand ="UPDATE [People] SET [LastName] = @LastName, [FirstName] = @FirstName, [CompanyName] = @CompanyName,
            [Email] = @Email, [Phone] = @Phone, [AltPhone] = @AltPhone, [Address1] = @Address1, [Address2]=@Address2, [State] = @State,
            [City] = @City, [Zipcode] = @Zipcode WHERE [PersonID] = @PersonID"
            DeleteCommand="DELETE FROM [People] WHERE [PersonID] = @PersonID">

            <UpdateParameters>
                <asp:Parameter Name="LastName" Type ="String" />
                <asp:Parameter Name="FirstName" Type ="String" />
                <asp:Parameter Name="CompanyName" Type ="String" />
                <asp:Parameter Name="Email" Type ="String" />
                <asp:Parameter Name="Phone" Type ="String" />
                <asp:Parameter Name="AltPhone" Type ="String" />
                <asp:Parameter Name="Address1" Type ="String" />
                <asp:Parameter Name="Address2" Type ="String" />
                <asp:Parameter Name="State" Type ="String" />
                <asp:Parameter Name="City" Type ="String" />
                <asp:Parameter Name="Zipcode" Type ="String" />
                <asp:Parameter Name="PersonID" Type ="Int32" />
            </UpdateParameters>

            <DeleteParameters>
                <asp:Parameter Name="PersonID" Type ="Int32" />
            </DeleteParameters>
        </asp:SqlDataSource>
        
    </div>


<%--<script src="scripts/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="scripts/bootstrap.min.js"></script>
<!-- DataTables -->
<script src="scripts/jquery.dataTables.min.js"></script>
<script src="scripts/dataTables.bootstrap.min.js"></script>

    <script>
        $(window).load(function () {
      $("#MainContent_GridView1").DataTable();
    
  });
</script>--%>

</asp:Content>
